[package]
name = "regex-bnf"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/arduano/regex-bnf/tree/master/regex-bnf"

[dependencies]
regex = "1.7.1"
regex-bnf-derive = { version = "0.1.0", path = "../regex-bnf-derive" }
thiserror = "1.0.38"
